## Remove the intermediate objects

rm("bodymag")
rm("bodyx")
rm("bodyy")
rm("bodyz")
rm("gravitymag")
rm("gravityx")
rm("gravityy")
rm("gravityz")
rm("headers")
rm("jerkmag")
rm("jerkx")
rm("jerky")
rm("jerkz")
rm("meanstdfields")
rm("merged")
rm("subjects")
rm("testFrame")
rm("tidy_headers")
rm("trainFrame")