## Summarize by subject and activity


## Set the groups for the summary
## Need to take into account alsto the movementtype and the axis
## because the table was made vertical by merging the compatible columns
summarized <- group_by(merged, subject, activity)

## Summarize the values
summarized <- summarize(summarized,
        timebodyaccelerometermeanx = mean(timebodyaccelerometermeanx),
		timebodyaccelerometermeany = mean(timebodyaccelerometermeany),
		timebodyaccelerometermeanz = mean(timebodyaccelerometermeanz),
		timebodyaccelerometerstandarddeviationx = mean(timebodyaccelerometerstandarddeviationx),
		timebodyaccelerometerstandarddeviationy = mean(timebodyaccelerometerstandarddeviationy),
		timebodyaccelerometerstandarddeviationz = mean(timebodyaccelerometerstandarddeviationz),
		timegravityaccelerometermeanx = mean(timegravityaccelerometermeanx),
		timegravityaccelerometermeany = mean(timegravityaccelerometermeany),
		timegravityaccelerometermeanz = mean(timegravityaccelerometermeanz),
		timegravityaccelerometerstandarddeviationx = mean(timegravityaccelerometerstandarddeviationx),
		timegravityaccelerometerstandarddeviationy = mean(timegravityaccelerometerstandarddeviationy),
		timegravityaccelerometerstandarddeviationz = mean(timegravityaccelerometerstandarddeviationz),
		timebodyaccelerometerjerkmeanx = mean(timebodyaccelerometerjerkmeanx),
		timebodyaccelerometerjerkmeany = mean(timebodyaccelerometerjerkmeany),
		timebodyaccelerometerjerkmeanz = mean(timebodyaccelerometerjerkmeanz),
		timebodyaccelerometerjerkstandarddeviationx = mean(timebodyaccelerometerjerkstandarddeviationx),
		timebodyaccelerometerjerkstandarddeviationy = mean(timebodyaccelerometerjerkstandarddeviationy),
		timebodyaccelerometerjerkstandarddeviationz = mean(timebodyaccelerometerjerkstandarddeviationz),
		timebodygyroscopemeanx = mean(timebodygyroscopemeanx),
		timebodygyroscopemeany = mean(timebodygyroscopemeany),
		timebodygyroscopemeanz = mean(timebodygyroscopemeanz),
		timebodygyroscopestandarddeviationx = mean(timebodygyroscopestandarddeviationx),
		timebodygyroscopestandarddeviationy = mean(timebodygyroscopestandarddeviationy),
		timebodygyroscopestandarddeviationz = mean(timebodygyroscopestandarddeviationz),
		timebodygyroscopejerkmeanx = mean(timebodygyroscopejerkmeanx),
		timebodygyroscopejerkmeany = mean(timebodygyroscopejerkmeany),
		timebodygyroscopejerkmeanz = mean(timebodygyroscopejerkmeanz),
		timebodygyroscopejerkstandarddeviationx = mean(timebodygyroscopejerkstandarddeviationx),
		timebodygyroscopejerkstandarddeviationy = mean(timebodygyroscopejerkstandarddeviationy),
		timebodygyroscopejerkstandarddeviationz = mean(timebodygyroscopejerkstandarddeviationz),
		timebodyaccelerometermagnitudemean = mean(timebodyaccelerometermagnitudemean),
		timebodyaccelerometermagnitudestandarddeviation = mean(timebodyaccelerometermagnitudestandarddeviation),
		timegravityaccelerometermagnitudemean = mean(timegravityaccelerometermagnitudemean),
		timegravityaccelerometermagnitudestandarddeviation = mean(timegravityaccelerometermagnitudestandarddeviation),
		timebodyaccelerometerjerkmagnitudemean = mean(timebodyaccelerometerjerkmagnitudemean),
		timebodyaccelerometerjerkmagnitudestandarddeviation = mean(timebodyaccelerometerjerkmagnitudestandarddeviation),
		timebodygyroscopemagnitudemean = mean(timebodygyroscopemagnitudemean),
		timebodygyroscopemagnitudestandarddeviation = mean(timebodygyroscopemagnitudestandarddeviation),
		timebodygyroscopejerkmagnitudemean = mean(timebodygyroscopejerkmagnitudemean),
		timebodygyroscopejerkmagnitudestandarddeviation = mean(timebodygyroscopejerkmagnitudestandarddeviation),
		frequencybodyaccelerometermeanx = mean(frequencybodyaccelerometermeanx),
		frequencybodyaccelerometermeany = mean(frequencybodyaccelerometermeany),
		frequencybodyaccelerometermeanz = mean(frequencybodyaccelerometermeanz),
		frequencybodyaccelerometerstandarddeviationx = mean(frequencybodyaccelerometerstandarddeviationx),
		frequencybodyaccelerometerstandarddeviationy = mean(frequencybodyaccelerometerstandarddeviationy),
		frequencybodyaccelerometerstandarddeviationz = mean(frequencybodyaccelerometerstandarddeviationz),
		frequencybodyaccelerometerjerkmeanx = mean(frequencybodyaccelerometerjerkmeanx),
		frequencybodyaccelerometerjerkmeany = mean(frequencybodyaccelerometerjerkmeany),
		frequencybodyaccelerometerjerkmeanz = mean(frequencybodyaccelerometerjerkmeanz),
		frequencybodyaccelerometerjerkstandarddeviationx = mean(frequencybodyaccelerometerjerkstandarddeviationx),
		frequencybodyaccelerometerjerkstandarddeviationy = mean(frequencybodyaccelerometerjerkstandarddeviationy),
		frequencybodyaccelerometerjerkstandarddeviationz = mean(frequencybodyaccelerometerjerkstandarddeviationz),
		frequencybodygyroscopemeanx = mean(frequencybodygyroscopemeanx),
		frequencybodygyroscopemeany = mean(frequencybodygyroscopemeany),
		frequencybodygyroscopemeanz = mean(frequencybodygyroscopemeanz),
		frequencybodygyroscopestandarddeviationx = mean(frequencybodygyroscopestandarddeviationx),
		frequencybodygyroscopestandarddeviationy = mean(frequencybodygyroscopestandarddeviationy),
		frequencybodygyroscopestandarddeviationz = mean(frequencybodygyroscopestandarddeviationz),
		frequencybodyaccelerometermagnitudemean = mean(frequencybodyaccelerometermagnitudemean),
		frequencybodyaccelerometermagnitudestandarddeviation = mean(frequencybodyaccelerometermagnitudestandarddeviation),
		frequencybodyaccelerometerjerkmagnitudemean = mean(frequencybodyaccelerometerjerkmagnitudemean),
		frequencybodyaccelerometerjerkmagnitudestandarddeviation = mean(frequencybodyaccelerometerjerkmagnitudestandarddeviation),
		frequencybodygyroscopemagnitudemean = mean(frequencybodygyroscopemagnitudemean),
		frequencybodygyroscopemagnitudestandarddeviation = mean(frequencybodygyroscopemagnitudestandarddeviation),
		frequencybodygyroscopejerkmagnitudemean = mean(frequencybodygyroscopejerkmagnitudemean),
		frequencybodygyroscopejerkmagnitudestandarddeviation = mean(frequencybodygyroscopejerkmagnitudestandarddeviation))